# Site wide configuration

title: Derick Ostrenko
locale: en_US
url: http://fredeerock.github.io

# for bookmarklet
github:
  repo: fredeerock/fredeerock.github.io
  branch: master

# Jekyll configuration

# permalink:   /:categories/:title/
permalink: /:title/
markdown:    kramdown
sass:
  sass_dir: _sass
  style: compressed
gems: ['jekyll-github-metadata', 'jekyll-sitemap']

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  enable_coderay: false


# Site owner
owner:
  name: Derick Ostrenko
  avatar: bio-photo.jpg
  bio: "Electronic artist & educator."
  email: dostrenko@gmail.com
  disqus-shortname:
  twitter: fredeerock
  facebook:
  google:
    plus:
    analytics: UA-12972540-1
    verify:
    ad-client:
    ad-slot:
  bing-verify:
  github: fredeerock
  stackoverflow: #123456/username   from a "http://stackoverflow.com/users/123456/username" link
  linkedin: dostrenko
  xing: #username
  instagram: #username
  lastfm: #username
  tumblr:
  pinterest: #username
  foursquare: #username
  steam: #username
  dribbble: #username
  youtube: #username
  soundcloud: #username
  weibo: #username
  flickr: fredeerock
  codepen: #username
  fullbio:  >
    Frederick “Derick” Ostrenko, is a media artist and Assistant Professor at Louisiana State University (LSU). He holds a joint-appointment in the Digital Art concentration at the School of Art and the Cultural Computing research group at the Center for Computation and Technology (CCT). Derick creates physical and virtual systems that examine the intersections of media, culture, and technology. He employs custom hardware and software that use various interfaces such as mobile applications, brain waves, generative visualizations, video processing, animation, and games. His research focuses on pushing art and technology to reveal hidden networks between people by creating structures for innovative forms of expression and discovery. Derick received his MFA in Digital+Media from the Rhode Island School of Design.
    Most recently Derick has shown his work at venues including the International Symposium of Electronic Art (Albuquerque, NM), New York University (New York, NY), Fountain Art Fair (Miami, FL), Buffalo Media Resources (Buffalo, NY), the Archie Bray Foundation (Helena, MT), the Polk Museum of Art (Lakeland, FL), NWEAMO (San Diego, CA), and the at the National Academy (New York, NY).
    In conjunction with his artistic practice, Ostrenko has also worked professionally in exhibit fabrication, video production, 3D modeling, and web development. As the current area head for Digital Art at the LSU School of Art, Derick teaches classes in animation, creative coding, 3D graphics, interactive art, and video production.
  shortbio: >
    Frederick “Derick” Ostrenko, is a media artist and Assistant Professor at Louisiana State University (LSU). He holds a joint-appointment in the Digital Art concentration at the School of Art and the Cultural Computing research group at the Center for Computation and Technology (CCT). Derick creates physical and virtual systems that examine the intersections of media, culture, and technology. He employs custom hardware and software that use various interfaces such as mobile applications, brain waves, generative visualizations, video processing, animation, and games. His research focuses on pushing art and technology to reveal hidden networks between people by creating structures for innovative forms of expression and discovery. Derick received his MFA in Digital+Media from the Rhode Island School of Design.

include: [".htaccess", ".well-known"]

keep_files: ["cms.html"]

exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules", "Gemfile", "Gemfile.lock", "LICENSE", "README.md", "vendor", "script"]
